latam_api.settings:
  type: config_object
  label: 'LATAM API Settings'
  mapping:
    invideo:
      type: mapping
      label: 'IndiVideo'
      mapping:
        enabled:
          type: boolean
          label: 'Enable IndiVideo integration'
        base_url:
          type: string
          label: 'IndiVideo base URL (must be individeo.com)'
        vars_json:
          type: text
          label: 'Personalization variables (JSON object)'
        render_mode:
          type: string
          label: 'Shortcode rendering mode (inline|link)'
        strict_host:
          type: boolean
          label: 'Restrict host to individeo.com'
        page_title:
          type: string
          label: 'Host page title'
        lang:
          type: string
          label: 'Default lang (injected if missing)'
        aspect_ratio:
          type: string
          label: 'Aspect ratio hint (e.g. 16:9)'
        cache_ttl:
          type: integer
          label: 'Host page cache max-age (seconds)'
